// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package walletdrpc is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	VersionRequest
	VersionResponse
	PingRequest
	PingResponse
	NetworkRequest
	NetworkResponse
	CreateWalletRequest
	CreateWalletResponse
*/
package walletdrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VersionRequest struct {
}

func (m *VersionRequest) Reset()                    { *m = VersionRequest{} }
func (m *VersionRequest) String() string            { return proto.CompactTextString(m) }
func (*VersionRequest) ProtoMessage()               {}
func (*VersionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type VersionResponse struct {
	VersionString string `protobuf:"bytes,1,opt,name=version_string,json=versionString" json:"version_string,omitempty"`
	Major         uint32 `protobuf:"varint,2,opt,name=major" json:"major,omitempty"`
	Minor         uint32 `protobuf:"varint,3,opt,name=minor" json:"minor,omitempty"`
	Patch         uint32 `protobuf:"varint,4,opt,name=patch" json:"patch,omitempty"`
	Prerelease    string `protobuf:"bytes,5,opt,name=prerelease" json:"prerelease,omitempty"`
	BuildMetadata string `protobuf:"bytes,6,opt,name=build_metadata,json=buildMetadata" json:"build_metadata,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VersionResponse) GetVersionString() string {
	if m != nil {
		return m.VersionString
	}
	return ""
}

func (m *VersionResponse) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *VersionResponse) GetMinor() uint32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *VersionResponse) GetPatch() uint32 {
	if m != nil {
		return m.Patch
	}
	return 0
}

func (m *VersionResponse) GetPrerelease() string {
	if m != nil {
		return m.Prerelease
	}
	return ""
}

func (m *VersionResponse) GetBuildMetadata() string {
	if m != nil {
		return m.BuildMetadata
	}
	return ""
}

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PingResponse struct {
}

func (m *PingResponse) Reset()                    { *m = PingResponse{} }
func (m *PingResponse) String() string            { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()               {}
func (*PingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type NetworkRequest struct {
}

func (m *NetworkRequest) Reset()                    { *m = NetworkRequest{} }
func (m *NetworkRequest) String() string            { return proto.CompactTextString(m) }
func (*NetworkRequest) ProtoMessage()               {}
func (*NetworkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type NetworkResponse struct {
	ActiveNetwork uint32 `protobuf:"varint,1,opt,name=active_network,json=activeNetwork" json:"active_network,omitempty"`
}

func (m *NetworkResponse) Reset()                    { *m = NetworkResponse{} }
func (m *NetworkResponse) String() string            { return proto.CompactTextString(m) }
func (*NetworkResponse) ProtoMessage()               {}
func (*NetworkResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *NetworkResponse) GetActiveNetwork() uint32 {
	if m != nil {
		return m.ActiveNetwork
	}
	return 0
}

type CreateWalletRequest struct {
	Pass string `protobuf:"bytes,1,opt,name=pass" json:"pass,omitempty"`
}

func (m *CreateWalletRequest) Reset()                    { *m = CreateWalletRequest{} }
func (m *CreateWalletRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateWalletRequest) ProtoMessage()               {}
func (*CreateWalletRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateWalletRequest) GetPass() string {
	if m != nil {
		return m.Pass
	}
	return ""
}

type CreateWalletResponse struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *CreateWalletResponse) Reset()                    { *m = CreateWalletResponse{} }
func (m *CreateWalletResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateWalletResponse) ProtoMessage()               {}
func (*CreateWalletResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateWalletResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionRequest)(nil), "walletdrpc.VersionRequest")
	proto.RegisterType((*VersionResponse)(nil), "walletdrpc.VersionResponse")
	proto.RegisterType((*PingRequest)(nil), "walletdrpc.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "walletdrpc.PingResponse")
	proto.RegisterType((*NetworkRequest)(nil), "walletdrpc.NetworkRequest")
	proto.RegisterType((*NetworkResponse)(nil), "walletdrpc.NetworkResponse")
	proto.RegisterType((*CreateWalletRequest)(nil), "walletdrpc.CreateWalletRequest")
	proto.RegisterType((*CreateWalletResponse)(nil), "walletdrpc.CreateWalletResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for VersionService service

type VersionServiceClient interface {
	Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error)
}

type versionServiceClient struct {
	cc *grpc.ClientConn
}

func NewVersionServiceClient(cc *grpc.ClientConn) VersionServiceClient {
	return &versionServiceClient{cc}
}

func (c *versionServiceClient) Version(ctx context.Context, in *VersionRequest, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/walletdrpc.VersionService/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VersionService service

type VersionServiceServer interface {
	Version(context.Context, *VersionRequest) (*VersionResponse, error)
}

func RegisterVersionServiceServer(s *grpc.Server, srv VersionServiceServer) {
	s.RegisterService(&_VersionService_serviceDesc, srv)
}

func _VersionService_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VersionServiceServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletdrpc.VersionService/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VersionServiceServer).Version(ctx, req.(*VersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VersionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "walletdrpc.VersionService",
	HandlerType: (*VersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _VersionService_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// Client API for WalletDaemonService service

type WalletDaemonServiceClient interface {
	// Queries
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Network(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*NetworkResponse, error)
	// Wallet
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error)
}

type walletDaemonServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletDaemonServiceClient(cc *grpc.ClientConn) WalletDaemonServiceClient {
	return &walletDaemonServiceClient{cc}
}

func (c *walletDaemonServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := grpc.Invoke(ctx, "/walletdrpc.WalletDaemonService/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDaemonServiceClient) Network(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*NetworkResponse, error) {
	out := new(NetworkResponse)
	err := grpc.Invoke(ctx, "/walletdrpc.WalletDaemonService/Network", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletDaemonServiceClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error) {
	out := new(CreateWalletResponse)
	err := grpc.Invoke(ctx, "/walletdrpc.WalletDaemonService/CreateWallet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WalletDaemonService service

type WalletDaemonServiceServer interface {
	// Queries
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Network(context.Context, *NetworkRequest) (*NetworkResponse, error)
	// Wallet
	CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error)
}

func RegisterWalletDaemonServiceServer(s *grpc.Server, srv WalletDaemonServiceServer) {
	s.RegisterService(&_WalletDaemonService_serviceDesc, srv)
}

func _WalletDaemonService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletdrpc.WalletDaemonService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDaemonService_Network_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServiceServer).Network(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletdrpc.WalletDaemonService/Network",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServiceServer).Network(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletDaemonService_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletDaemonServiceServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/walletdrpc.WalletDaemonService/CreateWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletDaemonServiceServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletDaemonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "walletdrpc.WalletDaemonService",
	HandlerType: (*WalletDaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _WalletDaemonService_Ping_Handler,
		},
		{
			MethodName: "Network",
			Handler:    _WalletDaemonService_Network_Handler,
		},
		{
			MethodName: "CreateWallet",
			Handler:    _WalletDaemonService_CreateWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x92, 0xd1, 0x4e, 0xfa, 0x30,
	0x14, 0xc6, 0xb3, 0xff, 0x1f, 0x30, 0x1c, 0x19, 0x98, 0x42, 0xe2, 0x32, 0x13, 0x25, 0x4b, 0x4c,
	0xd4, 0x0b, 0x2e, 0xf0, 0x46, 0x6f, 0xd5, 0x5b, 0x8d, 0x0e, 0xa3, 0x97, 0xa4, 0x6c, 0x27, 0x5a,
	0x1d, 0x5b, 0x6d, 0x3b, 0x78, 0x3e, 0x9f, 0xc6, 0xd7, 0x70, 0x6b, 0x0b, 0x6c, 0x8a, 0x77, 0x3d,
	0xbf, 0xf3, 0xad, 0xe7, 0x3b, 0x5f, 0x07, 0x6d, 0xca, 0xd9, 0x88, 0x8b, 0x4c, 0x65, 0x04, 0x96,
	0x34, 0x49, 0x50, 0xc5, 0x82, 0x47, 0xc1, 0x1e, 0x74, 0x9f, 0x50, 0x48, 0x96, 0xa5, 0x21, 0x7e,
	0xe4, 0x28, 0x55, 0xf0, 0xe9, 0x40, 0x6f, 0x8d, 0x24, 0xcf, 0x52, 0x89, 0xe4, 0x18, 0xba, 0x0b,
	0x83, 0xa6, 0x52, 0x09, 0x96, 0xbe, 0x78, 0xce, 0xd0, 0x39, 0x69, 0x87, 0xae, 0xa5, 0x13, 0x0d,
	0xc9, 0x00, 0x9a, 0x73, 0xfa, 0x96, 0x09, 0xef, 0x5f, 0xd1, 0x75, 0x43, 0x53, 0x68, 0xca, 0xd2,
	0x82, 0xfe, 0xb7, 0xb4, 0x2c, 0x4a, 0xca, 0xa9, 0x8a, 0x5e, 0xbd, 0x86, 0xa1, 0xba, 0x20, 0x87,
	0x00, 0x5c, 0xa0, 0xc0, 0x04, 0xa9, 0x44, 0xaf, 0xa9, 0x87, 0x54, 0x48, 0x69, 0x64, 0x96, 0xb3,
	0x24, 0x9e, 0xce, 0x51, 0xd1, 0x98, 0x2a, 0xea, 0xb5, 0x8c, 0x11, 0x4d, 0x6f, 0x2d, 0x0c, 0x5c,
	0xd8, 0xbd, 0x2f, 0x0c, 0xad, 0x56, 0xea, 0x42, 0xc7, 0x94, 0x66, 0x9d, 0x72, 0xe9, 0x3b, 0x54,
	0xcb, 0x4c, 0xbc, 0xaf, 0x14, 0x17, 0xd0, 0x5b, 0x93, 0xcd, 0xce, 0x34, 0x52, 0x6c, 0x81, 0xd3,
	0xd4, 0x74, 0xf4, 0xce, 0x6e, 0xe8, 0x1a, 0x6a, 0xe5, 0xc1, 0x29, 0xf4, 0xaf, 0x05, 0x52, 0x85,
	0xcf, 0x3a, 0x54, 0x7b, 0x21, 0x21, 0xd0, 0xe0, 0x54, 0x4a, 0x9b, 0x93, 0x3e, 0x07, 0x67, 0x30,
	0xa8, 0x4b, 0xed, 0xa4, 0x42, 0x9b, 0xe7, 0x2c, 0x5e, 0x69, 0xcb, 0xf3, 0xf8, 0x71, 0xfd, 0x2e,
	0x13, 0x14, 0x0b, 0x16, 0x21, 0xb9, 0x82, 0x1d, 0x4b, 0x88, 0x3f, 0xda, 0xbc, 0xe0, 0xa8, 0xfe,
	0x7c, 0xfe, 0xc1, 0xd6, 0x9e, 0x99, 0x34, 0xfe, 0x72, 0xa0, 0x6f, 0x86, 0xdf, 0x50, 0x9c, 0x6f,
	0xee, 0xbe, 0x84, 0x46, 0x19, 0x10, 0xd9, 0xaf, 0x7e, 0x5c, 0x49, 0xd0, 0xf7, 0x7e, 0x37, 0xac,
	0xf9, 0xc2, 0x96, 0x8d, 0xa2, 0x6e, 0xab, 0x1e, 0x70, 0xdd, 0xd6, 0xcf, 0xa8, 0x1f, 0xa0, 0x53,
	0x0d, 0x86, 0x1c, 0x55, 0xc5, 0x5b, 0xd2, 0xf5, 0x87, 0x7f, 0x0b, 0xcc, 0x95, 0xb3, 0x96, 0xfe,
	0xd5, 0xcf, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x24, 0x20, 0x50, 0xcd, 0xf7, 0x02, 0x00, 0x00,
}
